development:
    cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
    cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
    cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
    kairos_app_id: <%= ENV["KAIROS_APP_ID"]
    kairos_app_key: <%= ENV["KAIROS_APP_KEY"]
test:
    cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
    cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
    cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
    kairos_app_id: <%= ENV["KAIROS_APP_ID"]
    kairos_app_key: <%= ENV["KAIROS_APP_KEY"]

production:
    cloudinary_cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
    cloudinary_api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
    cloudinary_api_secret: <%= ENV["CLOUDINARY_API_SECRET"] %>
    kairos_app_id: <%= ENV["KAIROS_APP_ID"]
    kairos_app_key: <%= ENV["KAIROS_APP_KEY"]
